"""Initial migration

Revision ID: c94daa3cb5e7
Revises:
Create Date: 2025-11-30 23:16:10.187366

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c94daa3cb5e7"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_roles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("access_roles_pkey")),
        sa.UniqueConstraint("name", name=op.f("access_roles_name_key")),
    )
    op.create_table(
        "business_elements",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("business_elements_pkey")),
        sa.UniqueConstraint("name", name=op.f("business_elements_name_key")),
    )
    op.create_table(
        "access_roles_rules",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("read_permission", sa.Boolean(), nullable=False),
        sa.Column("read_all_permission", sa.Boolean(), nullable=False),
        sa.Column("create_permission", sa.Boolean(), nullable=False),
        sa.Column("update_permission", sa.Boolean(), nullable=False),
        sa.Column("update_all_permission", sa.Boolean(), nullable=False),
        sa.Column("delete_permission", sa.Boolean(), nullable=False),
        sa.Column("delete_all_permission", sa.Boolean(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("business_element_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_element_id"],
            ["business_elements.id"],
            name=op.f("access_roles_rules_business_element_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["access_roles.id"],
            name=op.f("access_roles_rules_role_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("access_roles_rules_pkey")),
        sa.UniqueConstraint(
            "role_id", "business_element_id", name="uq_role_business_element"
        ),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("surname", sa.String(length=50), nullable=False),
        sa.Column("patronymic", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("access_role_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["access_role_id"],
            ["access_roles.id"],
            name=op.f("users_access_role_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
    )
    op.create_index(op.f("users_email_idx"), "users", ["email"], unique=True)
    op.create_index(op.f("users_id_idx"), "users", ["id"], unique=False)
    op.create_table(
        "refresh_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("refresh_token", sa.UUID(), nullable=False),
        sa.Column("expires_in", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("refresh_sessions_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("refresh_sessions_pkey")),
    )
    op.create_index(
        op.f("refresh_sessions_id_idx"), "refresh_sessions", ["id"], unique=False
    )
    op.create_index(
        op.f("refresh_sessions_refresh_token_idx"),
        "refresh_sessions",
        ["refresh_token"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("refresh_sessions_refresh_token_idx"), table_name="refresh_sessions"
    )
    op.drop_index(op.f("refresh_sessions_id_idx"), table_name="refresh_sessions")
    op.drop_table("refresh_sessions")
    op.drop_index(op.f("users_id_idx"), table_name="users")
    op.drop_index(op.f("users_email_idx"), table_name="users")
    op.drop_table("users")
    op.drop_table("access_roles_rules")
    op.drop_table("business_elements")
    op.drop_table("access_roles")
    # ### end Alembic commands ###
